exclude:
  - src/
  - node_modules/
  - package*.json
  - vite.config.js
  - tailwind.config.js
  - postcss.config.js
  - .github/
  - README.md
  - LICENSE

include:
  - assets/
  - favicon.jpg
  - index.html
  - CNAME
  - .nojekyll